print("\t Krista Zaharieva ")
print("\t Krista\n\t Zaharieva ")
print(" Krista Zaharieva ".lstrip())
print(" Krista Zaharieva ".rstrip())
print(" Krista Zaharieva ".strip())
name = " Krista Zaharieva "
print(name.lstrip())
print(name.rstrip())
print(name.strip())
print("\t" + name.strip())
